### PR TITLE
Hoist jest mocks

### PR DESCRIPTION
**Pull request by Brooooooklyn**
Resolve https://github.com/Brooooooklyn/swc-node/issues/29

### CODE REVIEW

**Comment by Brooooooklyn** [comment]
I'm trying to write a custom transformer that apply to `swc Program`, which transform

```js
import { timer } from 'utils'
jest.mock('./utils')
describe('timer', () => {
  it('timer should work', () => {
    expect(timer()).toBe(1)
  })
})
jest.unmock()
```

to

```js
"use strict";
jest.mock('./utils');
var _utils = require("utils");
describe('timer', ()=>{
    it('timer should work', ()=>{
        expect(_utils.timer()).toBe(1);
    });
});
```

But I found that my `Fold` is always run after `CommonJS Fold`, so the output was like this:

```js
"use strict";
var _utils = require("utils");
jest.mock('./utils');
describe('timer', ()=>{
    it('timer should work', ()=>{
        expect(_utils.timer()).toBe(1);
    });
});
``` 

So how could I run my `JestHoistTransformer` after `CommonJS Fold`? @kdy1

**Comment by kdy1** [comment]
You have two options.

Applying jest transform using `fold_with(&mut jest_transform())` is the first option, and will be easier than the alternative.

The second option is manually using `PassBuilder` from swc crate.

https://github.com/swc-project/swc/blob/d641c0216b053275dfcfcbed7a8e0b2d20f79f93/src/config.rs#L190-L268

It has `.then`, which adds a pass to the builder. 

(Currently, there's no way to inject custom pass into `swc::Compiler` from rust. )

**Comment by Brooooooklyn** [comment]
> Applying jest transform using fold_with(&mut jest_transform()) is the first option

Actually I was apply it by:
```rust
  let jest_hoist_transformer = JestHoistTransformer::new();
  
  let program = c
    .parse_js(fm, jsc.target, syntax, true, need_parse_comment)
    .map_err(|e| Error::new(Status::GenericFailure, format!("Parse js failed {}", e)))?;

  c.process_js(
    c.transform(program, false, jest_hoist_transformer),
    register_options,
  )
```

But `process_js` will always apply `CommonJS Fold` after `jest_hoist_transformer`.

> The second option is manually using PassBuilder from swc crate.

In this way, how could I transform code without `Compiler` ?

**Comment by kdy1** [comment]
> But process_js will always apply CommonJS Fold after jest_hoist_transformer.

Ah... I think it's because common js prepends require statements.


> In this way, how could I transform code without Compiler ?

```rust
let pass = PassBuilder::new(&cm, &handler, loose, root_mark, pass)
            .target(target)
            .hygiene(!self.disable_hygiene)
            .fixer(!self.disable_fixer)
            .preset_env(config.env)
            .finalize(root_mark, syntax, config.module, comments);
```
`loose` is for es2015 passes. In loose mode, swc generates faster code while being less spec-compilant.
`pass` is your customized pass.

swc creates `pass` like (https://github.com/swc-project/swc/blob/d641c0216b053275dfcfcbed7a8e0b2d20f79f93/src/config.rs#L190-L268)

```rust
    let pass = chain!(
            // handle jsx
            Optional::new(react::react(cm.clone(), transform.react), syntax.jsx()),
            // Decorators may use type information
            Optional::new(
                decorators(decorators::Config {
                    legacy: transform.legacy_decorator,
                    emit_metadata: transform.decorator_metadata,
                }),
                syntax.decorators()
            ),
            Optional::new(typescript_class_properties(), syntax.typescript()),
            Optional::new(typescript::strip(), syntax.typescript()),
            resolver_with_mark(root_mark),
            const_modules,
            optimization,
            Optional::new(
                export(),
                syntax.export_default_from() || syntax.export_namespace_from()
            ),
            Optional::new(simplifier(Default::default()), enable_optimizer),
            json_parse_pass
        );
```
 

finalize adds fixer / resolver / module system / compatibility passes based on the given passes.



Btw, there's two root_mark (It's a bug...)

**Comment by kdy1** [comment]
Note: I think you should run your transform after common js module pass because even with second option, cjs module pass will prepend require statements.

**Comment by Brooooooklyn** [comment]
> In this way, how could I transform code without Compiler

I mean, I can build my pass from config myself, but how could I use this `pass` to transform my code?

I searched source codes from `swc`, the only API which take `BuiltConfig` is `process_js_inner`. But the `process_js_inner` is private method.

**Comment by Brooooooklyn** [comment]
How about provide `process_js_file_with_custom_pass` method in `Compiler`? 

```rust
fn process_js_with_custom_pass(
  &self,
  fm: Arc<SourceFile>,
  opts: &Options,
  custom_pass: P, 
)
```

**Comment by kdy1** [comment]
> I mean, I can build my pass from config myself, but how could I use this `pass` to transform my code?
> 
> I searched source codes from `swc`, the only API which take `BuiltConfig` is `process_js_inner`. But the `process_js_inner` is private method.

You can apply a transform like `module.fold_with(&mut jest_transform())`. Note that you should import `swc_ecma_visit::FoldWith`

**Comment by kdy1** [comment]
> How about provide `process_js_file_with_custom_pass` method in `Compiler`?
> 
> ```rust
> fn process_js_with_custom_pass(
>   &self,
>   fm: Arc<SourceFile>,
>   opts: &Options,
>   custom_after_pass: P, 
> )
> ```
> 
> `custom_after_pass` in argument would be appended into pass list.
> Users do not need `before pass` because they can easily transform the `program` before it's passed into `process_js` function.

Seems reasonable. I'll add it.

**Pull request merged**
